[tool.poetry]
name = "python_test"
version = "0.0.1"
description = ""

license = "MIT"

authors = [
    "Dimosthenis Michailidis <mrdimosthenis@hotmail.com>"
]

[tool.poetry.dependencies]
python = "~3.6"
toml = "^0.9"
PyFunctional = { version = "^1.3.0" }
dataclasses = { version = "^0.7" }