[tool.poetry]
name = "python_test"
version = "0.0.1"
description = ""

license = "MIT"

authors = [
    "Dimosthenis Michailidis <mrdimosthenis@hotmail.com>"
]

[tool.poetry.dependencies]
python = "~3.9"
toml = "^0.9"
synapses-py = { version = "^7.4.1" }
